In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures


In [25]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [26]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [28]:
print(x_)

[[0.000e+00 1.000e+00 0.000e+00 0.000e+00 1.000e+00]
 [5.000e+00 1.000e+00 2.500e+01 5.000e+00 1.000e+00]
 [1.500e+01 2.000e+00 2.250e+02 3.000e+01 4.000e+00]
 [2.500e+01 5.000e+00 6.250e+02 1.250e+02 2.500e+01]
 [3.500e+01 1.100e+01 1.225e+03 3.850e+02 1.210e+02]
 [4.500e+01 1.500e+01 2.025e+03 6.750e+02 2.250e+02]
 [5.500e+01 3.400e+01 3.025e+03 1.870e+03 1.156e+03]
 [6.000e+01 3.500e+01 3.600e+03 2.100e+03 1.225e+03]]


In [29]:
model = LinearRegression().fit(x_, y)


In [30]:
r_sq = model.score(x_, y)


In [31]:
print('coefficient of determination:', r_sq)




coefficient of determination: 0.9453701449127822


In [32]:
 print('intercept:', model.intercept_)


intercept: 0.8430556452395876


In [33]:
 print('coefficients:', model.coef_)

coefficients: [ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]


In [34]:
y_pred = model.predict(x_)


In [35]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]


In [39]:
x_new = np.arange(16).reshape((-1, 2))

In [40]:
print(x_new)


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [41]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x_new)

In [42]:
print(x_)


[[  0.   1.   0.   0.   1.]
 [  2.   3.   4.   6.   9.]
 [  4.   5.  16.  20.  25.]
 [  6.   7.  36.  42.  49.]
 [  8.   9.  64.  72.  81.]
 [ 10.  11. 100. 110. 121.]
 [ 12.  13. 144. 156. 169.]
 [ 14.  15. 196. 210. 225.]]


In [43]:
y_pred = model.predict(x_)


In [44]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[0.54047408 4.31209979 6.98376525 8.55547047 9.02721544 8.39900016
 6.67082464 3.84268887]
