In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures


In [3]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [4]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [5]:
print(x_)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]


In [6]:
model = LinearRegression().fit(x_, y)


In [7]:
r_sq = model.score(x_, y)


In [8]:
print('coefficient of determination:', r_sq)




coefficient of determination: 0.8908516262498564


In [9]:
 print('intercept:', model.intercept_)


intercept: 21.37232142857144


In [10]:
 print('coefficients:', model.coef_)

coefficients: [-1.32357143  0.02839286]


In [11]:
y_pred = model.predict(x_)


In [12]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


In [19]:
x_new = np.arange(6).reshape((-1, 1))

In [20]:
print(x_new)


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [21]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x_new)

In [22]:
print(x_)


[[ 0.  0.]
 [ 1.  1.]
 [ 2.  4.]
 [ 3.  9.]
 [ 4. 16.]
 [ 5. 25.]]


In [23]:
y_pred = model.predict(x_)


In [24]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[21.37232143 20.07714286 18.83875    17.65714286 16.53232143 15.46428571]
